#!/usr/bin/env bash
rsync -avz --progress summon.min.js summon.min.css live:~
echo 'now ssh in webserver and run this command (copied to your clipboard):'
cmd='sudo mv summon.min.* /opt/libraries_wagtail/libraries/libraries/static/summon/'
echo $cmd
echo $cmd | pbcopy
