#!/usr/bin/env bash
if [ -z $NS ]; then
    echo 'You must define the kubernetes namespace in an \$NS env var like "set -x NS namespace".' >&2
    exit 1
fi
# using my k8 kubectl wrapper
POD=$(k8 pod)
DIR=/app/libraries/static/summon
# must mkdir summon if it doesn't exist or the files are written to a file named "summon" instead
kubectl -n$NS exec -it $POD -- mkdir -v $DIR
# kubectl cp doesn't work with wildcards so we have to use xargs
ls summon.min.* | xargs -I{} kubectl cp {} $NS/$POD:$DIR/
