#!/usr/bin/env bash
if [ -z $NS ]; then
    echo 'You must define the kubernetes namespace in an \$NS env var like "set -x NS namespace".' >&2
    exit 1
fi
# using my k8 kubectl wrapper
POD=$(k8 pod)
# kubectl cp doesn't work with wildcards so we have to use xargs
ls summon.min.* | xargs -I{} kubectl cp {} $NS/$POD:/app/libraries/static/summon/
