#!/usr/bin/env fish
# date format ProQuest wants us to use
set curdate (date "+%F-%H-%M-%S")

set_color --bold
echo "what type of upload is this? (full, updates, deletes)"
set_color normal
read -p "echo -n 'type: '" type

# construct appropriate file name from info we have
set newfilename cca-catalog-$type-$curdate.mrc

set_color --bold
echo "where's the MARC file at?"
set_color normal
read --shell -p "echo -n 'path: '" -c "/Users/ephetteplace/Code/libraries-branding/summon/" filename

set_color --bold
cp -v $filename $newfilename
or exit 1

cat .password | pbcopy
echo "run the commands below to upload to Summon, the SFTP password is on your clipboard"
echo "sftp summon; put $newfilename $type"

set_color normal
